import { describe, it, expect } from 'vitest';
import fs from 'node:fs';

// The brand assets apps/ios/scripts/generate-app-icon.swift renders from
// packages/tokens/tokens.json (brand.mark). App Store validation refuses a
// primary icon with an alpha channel, so that's pinned here, along with the
// asset catalog wiring, the SVGs' colours against the tokens, and the contrast
// rules apps/ios/brand/README.md states.
const ICONS = 'apps/ios/AlgoMinutes/Resources/Assets.xcassets/AppIcon.appiconset';
const LOGO = 'apps/ios/AlgoMinutes/Resources/Assets.xcassets/Logo.imageset';
const tokens = JSON.parse(fs.readFileSync('packages/tokens/tokens.json', 'utf8'));
const mark: Record<string, string> = tokens.brand.mark;

/** A PNG's size and colour type (2 = RGB, 6 = RGB + alpha), from its IHDR chunk. */
function png(path: string) {
  const b = fs.readFileSync(path);
  expect(b.subarray(1, 4).toString('latin1')).toBe('PNG');
  expect(b.subarray(12, 16).toString('latin1')).toBe('IHDR');
  return { width: b.readUInt32BE(16), height: b.readUInt32BE(20), colourType: b[25] };
}

function luminance(hex: string): number {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
    .map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
function contrast(a: string, b: string): number {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

describe('app icon', () => {
  it('the primary icon is 1024 x 1024 with no alpha channel', () => {
    expect(png(`${ICONS}/AppIcon-1024.png`)).toEqual({ width: 1024, height: 1024, colourType: 2 });
  });

  it('the dark and tinted variants are 1024 x 1024 with alpha (iOS composites them)', () => {
    for (const v of ['dark', 'tinted']) {
      expect(png(`${ICONS}/AppIcon-1024-${v}.png`)).toEqual({ width: 1024, height: 1024, colourType: 6 });
    }
  });

  it('the asset catalog names exactly those three files', () => {
    const contents = JSON.parse(fs.readFileSync(`${ICONS}/Contents.json`, 'utf8'));
    expect(contents.images.map((i: { filename: string }) => i.filename).sort())
      .toEqual(['AppIcon-1024-dark.png', 'AppIcon-1024-tinted.png', 'AppIcon-1024.png']);
  });
});

describe('in-app logo', () => {
  it('is a vector PDF, kept as a vector', () => {
    const contents = JSON.parse(fs.readFileSync(`${LOGO}/Contents.json`, 'utf8'));
    expect(contents.images).toEqual([{ filename: 'logo.pdf', idiom: 'universal' }]);
    expect(contents.properties['preserves-vector-representation']).toBe(true);
    expect(fs.readFileSync(`${LOGO}/logo.pdf`).subarray(0, 5).toString('latin1')).toBe('%PDF-');
    expect(fs.readdirSync(LOGO).sort()).toEqual(['Contents.json', 'logo.pdf']);
  });
});

describe('brand SVGs', () => {
  const svg = (name: string) => fs.readFileSync(`apps/ios/brand/${name}.svg`, 'utf8');

  it("use the tokens' colours (they were generated from them, not edited)", () => {
    for (const name of ['icon', 'icon-rounded']) {
      const s = svg(name);
      expect(s).toContain(`stop-color="${mark.gradientStart}"`);
      expect(s).toContain(`stop-color="${mark.gradientEnd}"`);
      expect(s).toContain(`fill="${mark.dot}"`);
    }
    expect(svg('mark-on-dark')).toContain(`fill="${mark.glyph}" mask="url(#glyph)"`);
    expect(svg('mark-on-light')).toContain(`fill="${mark.gradientStart}" mask="url(#glyph)"`);
    expect(svg('mark-on-light')).toContain(`fill="${mark.dotOnLight}"`);
  });

  it('say they are generated', () => {
    for (const name of ['icon', 'icon-rounded', 'mark-on-dark', 'mark-on-light']) {
      expect(svg(name)).toContain('Generated by apps/ios/scripts/generate-app-icon.swift');
    }
  });
});

describe('brand contrast (apps/ios/brand/README.md)', () => {
  const appBackground = tokens.color.dark.bg; // Theme.background

  it('lavender is AA text on the dark app background', () => {
    expect(contrast(mark.lavender, appBackground)).toBeGreaterThanOrEqual(4.5);
  });

  it('white is AA on the brand purple, for a filled control', () => {
    expect(contrast('#FFFFFF', mark.gradientStart)).toBeGreaterThanOrEqual(4.5);
  });

  it('the brand purple is not text on dark (the README says so)', () => {
    expect(contrast(mark.gradientStart, appBackground)).toBeLessThan(4.5);
  });
});
